BROADCAST_PREFIX: '&b&lBROADCAST&7: '

NO_PERMISSION: '&4&lFAULT&7: You do not have permission to use this command!'

ENTER_ARGUMENT: '&4&lFAULT&7: Please use the right format!'

open:
   echest: '&aOpening your enderchest'
   workbench: '&aOpening a workbench'
   enchanttable: '&aOpening a enchanting table'
   servergui: '&bServer inventory'
   prefix: '&a&lOPENING&7: '
YouAreConsole: You are not a player!

SUCCESS: '&b&lSUCCESS&7: '

Prefixes:
   Prefix: '&b&l[&a&lGravity Essentials&b&l] &r'
AutoSave:
   msg: '&6Saving all worlds.'
   complete: '&b&lSUCCESS&7: &eAutosave has been completed!'
   interval: 10
   prefix: '&a&lAutoSaver &r'

