name: GravityEssentials
version: 1.0
main: net.GravityNetwork.Essentials.Main

commands:
   afk:
     usage: /<command>
     description: Set yourself away from keyboard.
     aliases: [eafk,away,eaway]
   broadcast:
     usage: /<command>
     description: Broadcast a message
     aliases: [bc,ebc,bcast,ebcast,ebroadcast,shout,eshout]
   viewinv:
     usage: /<command> <player>
     description: See the inventory of other players.
     aliases: [einvsee, invsee, seeinventory, seeinv]
   poke:
     usage: /<command> <player>
     description: Poke a player
   enderchest:
     usage: /<command>
     description: Open your enderchest
   enchanttable:
     usage: /<command>
     description: Open a enchant table
   craft:
     usage: /<command>
   shout:
     usage: /<command>
   gravityessentials:
     usage: /<command>
     description: The essentials plugin for Gravity Network
     aliases: [egravityessentials]
   server:
     usage: /<command>
     description: Join a server